# Generated by Django 4.2.7 on 2024-03-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0029_alter_usertoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usertoken',
        ),
    ]
